settings:
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book"
  new: "https://news.railstutorial.org/"
  ruby_on_rails_tutorial: "https://www.railstutorial.org/"
  michael_hartl: "https://www.michaelhartl.com/"
  contact: "https://www.railstutorial.org/contact"
  ruby_on_rails: "https://rubyonrails.org/"
  learn_enough: "https://learnenough.com/"
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  length_max_name: 25
  length_max_email: 50
  length_min_pass: 6
  expired_password_time: 2
  length_max_content: 140
  length_micropost: 50
  paging_numbers: 20
  length_user_info: 50
  image_type: ["image/jpeg", "image/gif", "image/png"]
  max_image_size: 5
  image_size_limit: [500,500]
gravatar:
  base_url: "https://www.gravatar.com/avatar"
  email_url: "https://gravatar.com/emails"
  size:
    default: 200
    index: 50
