settings:
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book"
  new: "https://news.railstutorial.org/"
  ruby_on_rails_tutorial: "https://www.railstutorial.org/"
  michael_hartl: "https://www.michaelhartl.com/"
  contact: "https://www.railstutorial.org/contact"
  ruby_on_rails: "https://rubyonrails.org/"
  learn_enough: "https://learnenough.com/"
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  length_max_name: 25
  length_max_email: 50
  length_min_pass: 6
